'use strict';
import {
  PROJECT_TYPE,
  ACT_TYPE,
  SEQUENCE_TYPE,
  SCENE_TYPE,
  BEAT_TYPE
} from 'APP/client/store/reducers/project';

const ACCEPTS_NOTHING = 'ACCEPTS_NOTHING';

export default {
  PROJECT_TYPE: [SEQUENCE_TYPE, SCENE_TYPE, BEAT_TYPE],
  ACT_TYPE: [ACT_TYPE, SEQUENCE_TYPE, 'HOT_SEAT'],
  SEQUENCE_TYPE: [SEQUENCE_TYPE, SCENE_TYPE, 'HOT_SEAT'],
  SCENE_TYPE: [SCENE_TYPE, BEAT_TYPE, 'HOT_SEAT'],
  BEAT_TYPE: [BEAT_TYPE, ACCEPTS_NOTHING, 'HOT_SEAT']
};
